### ISSUE TITLE
Ordering

### ISSUE THREAD

**Issue by KatieMishra** [gatorbotics1700/Practice#10]
- inner tubes
- RGB lights
- sensors

**Comment by doubletissue** [comment]
We should also get something to adapt from a phone to an ethernet port. A few options:
- microusb male to ethernet female
- microusb male to usb female, then usb male to ethernet female
- usb type c male to ethernet female
- usb type c male to usb female, then usb male to ethernet female

I suspect that a phone we get in the fall/winter will use usb type c. My phone uses it, but most others we test with will be microusb. Using multiple cables gives more points of failure, but a single cable will be specific to the port.
