### ISSUE TITLE
Look into Github-Slack integration

### ISSUE THREAD

**Issue by KatieMishra** [gatorbotics1700/Practice#17]

**Comment by doubletissue** [comment]
https://github.com/integrations/slack

**Comment by doubletissue** [comment]
Integration is set up to link "scratch" to "development-team" for now. It is done with my account, we should switch it to use the Gatorbotics Github account in the future.

**Comment by doubletissue** [comment]
Reassigning to @KatieMishra to do this with the Gatorbotics account and to make sure we are writing to the right channel.

**Comment by KatieMishra** [comment]
Depends on #22

**Comment by doubletissue** [comment]
Done, we can link each repository to a different channel should we choose to do so.
