### ISSUE TITLE
Teach Terminal/Git

### ISSUE THREAD

**Issue by KatieMishra** [gatorbotics1700/Practice#20]

**Comment by doubletissue** [comment]
Depends on #19

**Comment by doubletissue** [comment]
Git presentation: 

https://docs.google.com/presentation/d/10wv4CqF98C8yITAQfralRsQkxk-QpW4Fl_R2yeymHfU/edit?usp=sharing

**Comment by doubletissue** [comment]
Terminal Presentation:

https://docs.google.com/presentation/d/1xgEVAzGkvDDY16fw2dBuUXlkGbDiI39rrMBSKWcCQlM/edit?usp=sharing
